sudo: required
dist: xenial
language: node_js
node_js:
  - '8.9'
  - '9.2'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
- npm install -g @angular/cli
- (cd volontaria/src && npm install)

script:
- (cd volontaria/src && ng lint)
- (cd volontaria/src && ng test)
- (cd volontaria/src && ng serve &)
- (cd volontaria/src && ng e2e)
